make test more robust

diff --git a/tasks/test.yaml b/tasks/test.yaml
--- a/tasks/test.yaml
+++ b/tasks/test.yaml
@@ -8,9 +8,9 @@ tasks:
       - cmd: |
           ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-base:0.34.1-upstream --confirm
           ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-identity-authorization:0.34.1-upstream --confirm
-          # if curl -s https://sso.uds.dev | grep -q "Username"; then
-          #   echo "Successfully hit Keycloak through MetalLB"
-          # else
-          #   echo "Failed to make a request to Keycloak through MetalLB"
-          #   exit 1
-          # fi
+          if docker run  --network=k3d-uds --add-host sso.uds.dev:172.18.1.1 curlimages/curl:latest curl -L https://sso.uds.dev | grep -q "Account Management"; then
+            echo "Successfully hit Keycloak through MetalLB"
+          else
+            echo "Failed to make a request to Keycloak through MetalLB"
+            exit 1
+          fi
