make tests actually tests (duh)

diff --git a/tasks/test.yaml b/tasks/test.yaml
--- a/tasks/test.yaml
+++ b/tasks/test.yaml
@@ -3,14 +3,14 @@
 
 tasks:
   - name: all
-    description: Create and deploy an Nginx package to test that MetalLB lets traffic through
+    description: Create and deploy the base and IDAM layers of UDS Core to test that MetalLB lets traffic through
     actions:
       - cmd: |
-          ./uds zarf package create tests/ --confirm
-          ./uds zarf package deploy zarf-package-nginx-amd64.tar.zst --confirm
-          if curl -s https://hello.uds.dev | grep -q "Welcome to nginx!"; then
-            echo "Successfully hit Nginx through MetalLB"
-          else
-            echo "Failed to make a request to Nginx through MetalLB"
-            exit 1
-          fi
+          ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-base:0.34.1-upstream --confirm
+          ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-identity-authorization:0.34.1-upstream --confirm
+          # if curl -s https://sso.uds.dev | grep -q "Username"; then
+          #   echo "Successfully hit Keycloak through MetalLB"
+          # else
+          #   echo "Failed to make a request to Keycloak through MetalLB"
+          #   exit 1
+          # fi
